### PR TITLE
Add more functionality

### PR DESCRIPTION
**Pull request by illia-romanenko**
Hi! We use stripe-dart quite extensively and added a lot of new fields. Please take a look and let us know what you think.

### CODE REVIEW

**Comment by enyo** [comment]
Hi @illia-romanenko . I'm not actively working on this project anymore. Would you like to become a maintainer? I would give you write access to this repo and the pub.dev library so you could publish it on your own.

**Comment by illia-romanenko** [comment]
Sure, I can help with it. We maintain more packages under https://github.com/solid-software so if you want to transfer it - we can dedicate more time to it. Or I can just help in your repo as well. Thanks!

**Comment by enyo** [comment]
@illia-romanenko I've given you push rights on this repo. Please give me your email address to use on pub.dev as well, so I can add you as maintainer there as well.

I'd like to keep the repo under enyo/* for now, but we can transfer in a few months if you intend on staying the maintainer.

**Comment by illia-romanenko** [comment]
> @illia-romanenko I've given you push rights on this repo. Please give me your email address to use on pub.dev as well, so I can add you as maintainer there as well.
> 
> I'd like to keep the repo under enyo/* for now, but we can transfer in a few months if you intend on staying the maintainer.

Great - thanks @enyo! Please use hello@solid.software for pub.dev.

**Comment by illia-romanenko** [comment]
I see other PRs coming - so let's merge this big one to make sure that other's don't need to duplicate our efforts here.

**Pull request merged**
